### PR TITLE
Nightmode

### PR DESCRIPTION
**Pull request by pauloconnor**
There are a few elements that don't change for nightmode, in particular buttons and drop downs but it's designed more for fullscreen of dashboard. Nightmode will persist while selecting Fullscreen.

Addresses https://github.com/obfuscurity/descartes/issues/109

### CODE REVIEW

**Comment by scalp42** [comment]
unrelated to anything I feel like I know you since 2012 @obfuscurity (dont think you ever changed your profile picture 😂)

**Comment by damm** [comment]
Blast from the past to even get a notification on issues related to graphite for me.

**Pull request closed without merging**
